const strings = {
  locale: 'es-AR',
  app: {
    title: 'Procesador Opciones',
    construction: 'La aplicación está en construcción.',
  },
  navigation: {
    processor: 'Procesador',
    settings: 'Configuración',
  },
  processor: {
    filters: {
      filterLabel: 'Filtrar por instrumento',
      all: 'Todos',
    },
    operationTypeTabs: {
      opciones: 'Opciones',
      compraVenta: 'Compra y Venta',
      arbitrajes: 'Arbitrajes de Plazo',
      ariaLabel: 'Seleccionar tipo de operación',
    },
    viewControls: {
      previewLabel: 'Vista de resultados',
      callsTab: 'CALLS',
      putsTab: 'PUTS',
      settingsButton: 'Ir a Configuración',
      previewAriaLabel: 'Seleccionar vista de resultados',
    },
    upload: {
      title: 'Procesar operaciones',
      description: 'Seleccioná un archivo CSV con tus operaciones para generar el informe.',
      selectButton: 'Seleccionar archivo',
      noFileSelected: 'Ningún archivo seleccionado',
      processButton: 'Procesar',
      processing: 'Procesando...',
      averagingSwitch: 'Promediar por strike',
    },
    summary: {
      title: 'Resumen',
      calls: 'CALLS',
      puts: 'PUTS',
      total: 'Total',
      averagingOn: 'Promedios activados',
      averagingOff: 'Promedios desactivados',
      processedAt: 'Procesado el',
    },
    actions: {
      title: 'Acciones',
      currentViewPrefix: 'Vista actual:',
      copyActive: 'Copiar vista actual',
      downloadActive: 'Descargar vista actual',
      scopeSection: 'Acciones por conjunto específico',
      viewNames: {
        CALLS: 'CALLS',
        PUTS: 'PUTS',
      },
      copyCalls: 'Copiar CALLS',
      copyPuts: 'Copiar PUTS',
      copyCombined: 'Copiar combinados',
      copySuccess: 'Datos copiados al portapapeles.',
      copyError: 'No se pudo copiar los datos. Intentalo nuevamente.',
      downloadCalls: 'Descargar CALLS',
      downloadPuts: 'Descargar PUTS',
      downloadCombined: 'Descargar combinados',
      downloadAll: 'Descargar todo',
      downloadError: 'No se pudo generar el archivo para descargar.',
      copy: 'Copiar',
      download: 'Descargar',
    },
    tables: {
      callsTitle: 'Operaciones CALLS',
      putsTitle: 'Operaciones PUTS',
      buyTitle: 'Operaciones de Compra',
      sellTitle: 'Operaciones de Venta',
      buySellPairsTitle: 'Pares Compra/Venta',
      arbitrajesTitle: 'Arbitrajes de Plazo',
      quantity: 'Cantidad',
      strike: 'Strike',
      price: 'Precio',
      symbol: 'Símbolo',
      settlement: 'Plazo',
      side: 'Operación',
      empty: 'Sin datos para mostrar.',
      inferredTooltip: 'Datos inferidos automáticamente a partir del token detectado.',
      comingSoon: 'Esta funcionalidad estará disponible próximamente.',
      averageByInstrument: 'Promediar',
      averageTooltip: 'Promediar por instrumento y plazo',
    },
    warnings: {
      largeFile: 'El archivo supera las 25.000 filas. El procesamiento puede demorar.',
      parseErrors: 'Se detectaron filas con errores durante el análisis del archivo.',
      maxRowsExceeded: 'Se alcanzó el límite de 50.000 filas. Verificá que el archivo esté completo.',
    },
    errors: {
      processingFailed: 'No se pudo procesar el archivo. Verificá el formato e intentá de nuevo.',
    },
  },
  settings: {
    title: 'Configuración',
    description:
      'Personalizá los prefijos, vencimientos y preferencias que usa el procesador para filtrar tus operaciones.',
    navigation: {
      prefixes: 'Prefijos de Opciones',
      expirations: 'Vencimientos',
    },
    storageDisabled:
      'No pudimos acceder al almacenamiento local. Los cambios que hagas no se van a guardar al cerrar la aplicación.',
    resetButton: 'Restaurar valores por defecto',
    resetDescription: 'Volvé a la configuración inicial definida por la aplicación.',
    placeholderTitle: 'Configuración en construcción',
    placeholderBody:
      'Aquí vas a administrar símbolos, vencimientos y preferencias de procesamiento una vez habilitado.',
    prefixes: {
      title: 'Prefijos de opciones',
      description: 'Mapeá los prefijos de los tokens con sus símbolos y definí cómo formatear strikes.',
      prefixLabel: 'Prefijo',
      prefixPlaceholder: 'Ej. GFG',
      symbolLabel: 'Símbolo',
      symbolPlaceholder: 'Ej. GGAL',
      defaultDecimalsLabel: 'Decimales por defecto',
      addButton: 'Agregar prefijo',
      emptyState: 'Agregá un prefijo para configurarlo.',
      errorRequired: 'Ingresá el prefijo y el símbolo.',
      rule: {
        ruleTitle: 'Prefijo {prefix}',
        ruleSubtitle: '{count} vencimientos configurados',
        removeRule: 'Eliminar prefijo',
        symbolLabel: 'Símbolo mapeado',
        symbolHelper: 'Se usa para agrupar las operaciones vinculadas al prefijo.',
        defaultDecimalsLabel: 'Decimales por defecto',
        decimalsHelper: 'Cantidad de decimales aplicada al strike cuando no hay overrides.',
        expirationCodeLabel: 'Código de vencimiento',
        expirationCodeHelper: 'Usá el sufijo del vencimiento (por ejemplo O, ENE, MAR).',
        expirationDecimalsLabel: 'Decimales',
        addExpirationOverride: 'Agregar vencimiento',
        availableExpirationCodes: 'Sufijos disponibles: {codes}',
        noExpirationOverrides: 'Agregá un vencimiento para personalizar los decimales.',
        expirationEntryLabel: 'Decimales para {code}',
        removeExpirationOverride: 'Quitar vencimiento',
        strikeTokenLabel: 'Token de strike',
        strikeTokenHelper: 'Parte numérica del token, por ejemplo 47343.',
        strikeDecimalsLabel: 'Decimales',
        addStrikeOverride: 'Agregar override de strike',
        noStrikeOverrides: 'No hay overrides específicos para este vencimiento.',
        removeStrikeOverride: 'Quitar override',
        decimalsDisplay: 'Decimales configurados: {value}',
      },
    },
    expirations: {
      title: 'Vencimientos',
      description: 'Configurá los vencimientos disponibles y administrá sus sufijos.',
      nameLabel: 'Nombre del vencimiento',
      namePlaceholder: 'Ej. Marzo',
      suffixLabel: 'Sufijo',
      suffixPlaceholder: 'Ej. MAR',
      helper: 'Podés reutilizar el nombre para agregar más sufijos.',
      suffixHelper: 'Los sufijos se guardan en mayúsculas.',
      addButton: 'Agregar',
      errorNameRequired: 'Ingresá un nombre de vencimiento.',
      errorSuffixRequired: 'Ingresá al menos un sufijo.',
      errorSuffixDuplicate: 'Ese sufijo ya existe para este vencimiento.',
      listLabel: 'Vencimientos configurados',
      emptyState: 'Agregá un vencimiento para que aparezca en la lista.',
      activeLabel: 'Vencimiento activo',
      removeLabel: 'Eliminar vencimiento',
      removeSuffixLabel: 'Quitar sufijo',
    },
  },
};

export default strings;
