const strings = {
  locale: 'es-AR',
  app: {
    title: '@ChuchoTrader',
    construction: 'La aplicación está en construcción.',
  },
  navigation: {
    processor: 'Operaciones',
    settings: 'Configuración',
    broker: 'Broker',
    settingsGeneral: 'Instrumentos',
    settingsFees: 'Comisiones',
  },
  processor: {
    filters: {
      filterLabel: 'Filtrar por instrumento',
      all: 'Todos',
    },
    operationTypeTabs: {
      opciones: 'Opciones',
      compraVenta: 'Compra y Venta',
      arbitrajes: 'Arbitrajes de Plazo',
      ariaLabel: 'Seleccionar tipo de operación',
    },
    viewControls: {
      previewLabel: 'Vista de resultados',
      callsTab: 'CALLS',
      putsTab: 'PUTS',
      settingsButton: 'Ir a Configuración',
      previewAriaLabel: 'Seleccionar vista de resultados',
    },
    upload: {
      title: 'Procesar operaciones',
      description: 'Seleccioná un archivo CSV con tus operaciones para generar el informe.',
      selectButton: 'Seleccionar archivo',
      noFileSelected: 'Ningún archivo seleccionado',
      processButton: 'Procesar',
      processing: 'Procesando...',
      averagingSwitch: 'Promediar por strike',
      instructions: {
        title: 'Instrucciones:',
        step1: '✓ Descargá el archivo CSV desde Matriz (ej: https://matriz.cocos.xoms.com.ar/)',
        step2: '✓ Usá el ícono de descarga a la derecha de "Reporte de operaciones" ("Descargar reporte de operaciones")',
        step3: '✓ Seleccioná el archivo CSV descargado',
        step4: '✓ Una vez procesado, podrás filtrar, copiar y descargar los resultados',
      },
      orDivider: 'ó',
      chooseMethodTitle: 'Cargá tus operaciones',
      chooseMethodDescription: 'Elegí una de las siguientes opciones para importar tus operaciones:',
      csvOption: 'Subir archivo CSV',
      brokerOption: 'Conectar con Broker',
    },
    sourcesIndicator: {
      title: 'Operaciones en memoria',
      brokerLabel: 'Broker',
      csvLabel: 'CSV',
      totalLabel: 'Total',
      otherLabel: 'Otros',
    },
    summary: {
      title: 'Resumen',
      calls: 'CALLS',
      puts: 'PUTS',
      total: 'Total',
      averagingOn: 'Promedios activados',
      averagingOff: 'Promedios desactivados',
      processedAt: 'Procesado el',
    },
    actions: {
      title: 'Acciones',
      currentViewPrefix: 'Vista actual:',
      copyActive: 'Copiar vista actual',
      downloadActive: 'Descargar vista actual',
      scopeSection: 'Acciones por conjunto específico',
      viewNames: {
        CALLS: 'CALLS',
        PUTS: 'PUTS',
      },
      copyCalls: 'Copiar CALLS',
      copyPuts: 'Copiar PUTS',
      copyCombined: 'Copiar combinados',
      copySuccess: 'Datos copiados al portapapeles.',
      copyError: 'No se pudo copiar los datos. Intentalo nuevamente.',
      downloadCalls: 'Descargar CALLS',
      downloadPuts: 'Descargar PUTS',
      downloadCombined: 'Descargar combinados',
      downloadAll: 'Descargar todo',
      downloadError: 'No se pudo generar el archivo para descargar.',
      copy: 'Copiar',
      download: 'Descargar',
    },
    tables: {
      callsTitle: 'Operaciones CALLS',
      putsTitle: 'Operaciones PUTS',
      buyTitle: 'Operaciones de Compra',
      sellTitle: 'Operaciones de Venta',
      buySellPairsTitle: 'Pares Compra/Venta',
      arbitrajesTitle: 'Arbitrajes de Plazo',
      quantity: 'Cantidad',
      strike: 'Strike',
      price: 'Precio',
      symbol: 'Símbolo',
      settlement: 'Plazo',
      side: 'Operación',
      fee: 'Gastos',
      netTotal: 'Neto',
      empty: 'Sin datos para mostrar.',
      inferredTooltip: 'El strike se detecta automáticamente del texto de la opción. Si es incorrecto, configurá los prefijos en Configuración para determinar el strike correctamente.',
      comingSoon: 'Esta funcionalidad estará disponible próximamente.',
      averageByInstrument: 'Promediar',
      averageTooltip: 'Promediar por instrumento y plazo',
      feeTooltipLabels: {
        categoria: 'Categoría',
        bruto: 'Bruto',
        comision: 'Comisión',
        derechos: 'Derechos',
        iva: 'IVA',
        total: 'Total',
        neto: 'Neto',
        fuente: 'Fuente',
        proximamente: 'Próximamente',
        categoriaFallback: 'Categoría (fallback)',
      },
    },
    warnings: {
      largeFile: 'El archivo supera las 25.000 filas. El procesamiento puede demorar.',
      parseErrors: 'Se detectaron filas con errores durante el análisis del archivo.',
      maxRowsExceeded: 'Se alcanzó el límite de 50.000 filas. Verificá que el archivo esté completo.',
    },
    errors: {
      processingFailed: 'No se pudo procesar el archivo. Verificá el formato e intentá de nuevo.',
    },
  },
  brokerSync: {
    loginTitle: 'Iniciar sesión broker',
    loginButton: 'Ingresar',
    loginError: 'Error de autenticación. Verificá tus credenciales.',
    inProgress: 'Sincronizando operaciones...',
    cancel: 'Cancelar',
    canceled: 'Sincronización cancelada.',
    lastSync: 'Última sincronización',
    refresh: 'Actualizar',
    noNewOperations: 'No hay nuevas operaciones.',
    rateLimited: 'Límite de velocidad alcanzado. Intentando nuevamente...',
    rateLimitedWait: 'Límite de velocidad alcanzado. Intentá nuevamente en ~{seconds} segundos.',
    retrying: 'Reintentando...',
    manualTrigger: 'Sincronizar ahora',
    accountSwitch: 'Cambiar cuenta',
    refreshSuccess: 'Se importaron {count} operaciones nuevas.',
    importedCount: 'Operaciones nuevas: {count}',
  refreshError: 'Ocurrió un error al actualizar las operaciones.',
    sessionExpired: 'La sesión expiró. Volvé a iniciar sesión.',
    sources: {
      broker: 'Broker',
      csv: 'CSV',
      total: 'Total',
      other: 'Otros',
    },
    modes: {
      daily: 'Sincronización completada',
      refresh: 'Actualización completada',
    },
  },
  settings: {
    title: 'Configuración',
    description:
      'Personalizá los prefijos, vencimientos y preferencias que usa la aplicación para filtrar tus operaciones.',
    navigation: {
      prefixes: 'Prefijos de Opciones',
      expirations: 'Vencimientos',
      broker: 'Broker',
    },
    storageDisabled:
      'No pudimos acceder al almacenamiento local. Los cambios que hagas no se van a guardar al cerrar la aplicación.',
    resetButton: 'Restaurar valores por defecto',
    resetDescription: 'Volvé a la configuración inicial definida por la aplicación.',
    placeholderTitle: 'Configuración en construcción',
    placeholderBody:
      'Aquí vas a administrar símbolos, vencimientos y preferencias de procesamiento una vez habilitado.',
    prefixes: {
      title: 'Prefijos de opciones',
      description: 'Mapeá los prefijos de los tokens con sus símbolos y definí cómo formatear strikes.',
      prefixLabel: 'Prefijo',
      prefixPlaceholder: 'Ej. GFG',
      symbolLabel: 'Símbolo',
      symbolPlaceholder: 'Ej. GGAL',
      defaultDecimalsLabel: 'Decimales por defecto',
      addButton: 'Agregar prefijo',
      emptyState: 'Agregá un prefijo para configurarlo.',
      errorRequired: 'Ingresá el prefijo y el símbolo.',
      rule: {
        ruleTitle: 'Prefijo {prefix}',
        ruleSubtitle: '{count} vencimientos configurados',
        removeRule: 'Eliminar prefijo',
        symbolLabel: 'Símbolo mapeado',
        symbolHelper: 'Se usa para agrupar las operaciones vinculadas al prefijo.',
        defaultDecimalsLabel: 'Decimales por defecto',
        decimalsHelper: 'Cantidad de decimales aplicada al strike cuando no hay overrides.',
        expirationCodeLabel: 'Código de vencimiento',
        expirationCodeHelper: 'Usá el sufijo del vencimiento (por ejemplo O, ENE, MAR).',
        expirationDecimalsLabel: 'Decimales',
        addExpirationOverride: 'Agregar vencimiento',
        availableExpirationCodes: 'Sufijos disponibles: {codes}',
        noExpirationOverrides: 'Agregá un vencimiento para personalizar los decimales.',
        expirationEntryLabel: 'Decimales para {code}',
        removeExpirationOverride: 'Quitar vencimiento',
        strikeTokenLabel: 'Token de strike',
        strikeTokenHelper: 'Parte numérica del token, por ejemplo 47343.',
        strikeDecimalsLabel: 'Decimales',
        addStrikeOverride: 'Agregar override de strike',
        noStrikeOverrides: 'No hay overrides específicos para este vencimiento.',
        removeStrikeOverride: 'Quitar override',
        decimalsDisplay: 'Decimales configurados: {value}',
      },
    },
    expirations: {
      title: 'Vencimientos',
      description: 'Configurá los vencimientos disponibles y administrá sus sufijos.',
      nameLabel: 'Nombre del vencimiento',
      namePlaceholder: 'Ej. Marzo',
      suffixLabel: 'Sufijo',
      suffixPlaceholder: 'Ej. MAR',
      helper: 'Podés reutilizar el nombre para agregar más sufijos.',
      suffixHelper: 'Los sufijos se guardan en mayúsculas.',
      addButton: 'Agregar',
      errorNameRequired: 'Ingresá un nombre de vencimiento.',
      errorSuffixRequired: 'Ingresá al menos un sufijo.',
      errorSuffixDuplicate: 'Ese sufijo ya existe para este vencimiento.',
      listLabel: 'Vencimientos configurados',
      emptyState: 'Agregá un vencimiento para que aparezca en la lista.',
      activeLabel: 'Vencimiento activo',
      removeLabel: 'Eliminar vencimiento',
      removeSuffixLabel: 'Quitar sufijo',
    },
    symbolSettings: {
      title: 'Configuración de Símbolos',
      description: 'Administrá las configuraciones por símbolo (prefijo, decimales, vencimientos).',
      addSymbolButton: 'Agregar Símbolo',
      addSymbolTitle: 'Nuevo Símbolo',
      symbolLabel: 'Símbolo',
      symbolPlaceholder: 'Ej. GGAL',
      symbolHelper: 'El símbolo debe ser único.',
      prefixLabel: 'Prefijo de opciones',
      prefixPlaceholder: 'Ej. GFG',
      defaultDecimalsLabel: 'Decimales predeterminados',
      resetButton: 'Restablecer a guardado',
      resetConfirm: '¿Descartar cambios y restablecer la configuración guardada?',
      saveSuccess: 'Configuración guardada',
      deleteSymbolButton: 'Eliminar símbolo',
      deleteSymbolTitle: 'Eliminar Símbolo',
      deleteSymbolConfirm: '¿Estás seguro que querés eliminar el símbolo "{symbol}"? Esta acción no se puede deshacer.',
      deleteSymbolSuccess: 'Símbolo eliminado',
      restoreDefaultsButton: 'Restaurar valores predeterminados',
      restoreDefaultsTitle: 'Restaurar Configuración',
      restoreDefaultsConfirm: '¿Estás seguro que querés restaurar todas las configuraciones a los valores predeterminados? Se eliminarán todos los símbolos y se restaurarán los valores por defecto. Esta acción no se puede deshacer.',
      restoreDefaultsSuccess: 'Configuración restaurada',
      errorSymbolRequired: 'Ingresá un símbolo.',
      errorSymbolInvalid: 'El símbolo debe contener solo letras y números.',
      errorSymbolDuplicate: 'Ese símbolo ya existe.',
      errorPrefixRequired: 'Ingresá un prefijo.',
      errorPrefixInvalid: 'El prefijo debe contener solo letras y números.',
      errorDecimalsInvalid: 'Los decimales deben estar entre 0 y 4.',
      noSymbolsState: 'Agregá un símbolo para comenzar.',
      tabAriaLabel: 'Pestañas de símbolos',
      symbolDefaultsTitle: 'Configuración General',
      symbolDefaultsDescription: 'Ajustá el prefijo y los decimales predeterminados para este símbolo.',
      prefixHelperText: 'Prefijo usado para identificar las opciones de este símbolo en el mercado. Ejemplo: GFG para GGAL, donde las opciones se identifican como GFGC47343O (call) o GFGV60000MAR (put).',
      decimalsHelperText: 'Cantidad de decimales (0-4) para formatear strikes. Define cómo se muestra el strike en las opciones procesadas. Ejemplos con prefijo "GFG": token "GFGC47343O" → 4734.3 (1 decimal), "GFGV60000MAR" → 600.00 (2 decimales).',
      errorSaveFailed: 'Error al guardar la configuración.',
      expirationTabs: {
        title: 'Vencimientos',
        suffixLabel: 'Sufijos permitidos',
        suffixHelper: 'Usá 1 o 2 letras (Ej. O, OC).',
        errorSuffixRequired: 'Ingresá un sufijo.',
        errorSuffixDuplicate: 'Ese sufijo ya existe.',
        decimalsLabel: 'Decimales para este vencimiento',
        decimalsHelper: 'Cantidad de decimales (0-4) específica para este vencimiento. Sobrescribe el valor predeterminado del símbolo. Permite formatear strikes diferentes según cada vencimiento.',
        overridesTitle: 'Ajustes de strike',
        overridesDescription: 'Personalizá el formateo de strikes específicos.',
        noOverrides: 'No hay overrides configurados para este vencimiento.',
        noExpirationSelected: 'Seleccioná un vencimiento para configurar.',
        addOverrideButton: 'Agregar ajuste',
        rawTokenLabel: 'Valor sin formato',
        rawTokenPlaceholder: 'Ej. 47343',
        formattedLabel: 'Valor formateado',
        formattedPlaceholder: 'Ej. 4734.3',
        removeOverrideLabel: 'Eliminar ajuste',
        errorRawRequired: 'Ingresá un valor sin formato.',
        errorRawInvalid: 'El valor debe ser numérico.',
        errorRawDuplicate: 'Ese valor ya tiene un ajuste.',
        errorFormattedRequired: 'Ingresá el valor formateado.',
      },
    },
    broker: {
      title: 'Configuración del Broker',
      description: 'Configurá la URL de la API del broker para sincronizar operaciones automáticamente.',
      apiUrlLabel: 'URL Base de la API',
      apiUrlPlaceholder: 'https://api.remarkets.primary.com.ar',
      apiUrlHelper: 'URL base del servidor de API del broker (jsRofex). Debe comenzar con http:// o https://.',
      brokerSelectLabel: 'Seleccioná tu broker',
      customUrlOption: 'URL Personalizada',
      saveButton: 'Guardar',
      saveSuccess: 'Configuración del broker guardada correctamente.',
      saveError: 'Error al guardar la configuración del broker.',
      errorUrlRequired: 'Ingresá una URL.',
      errorUrlInvalid: 'La URL debe ser válida y comenzar con http:// o https://.',
      testConnectionButton: 'Probar conexión',
      testConnectionSuccess: 'Conexión exitosa.',
      testConnectionError: 'Error al conectar con el broker.',
    },
    brokerFees: {
      title: 'Comisiones',
      description: 'Configurá las comisiones que aplica tu broker para usarlas en el cálculo automático de gastos.',
      commissionLabel: 'Comisión sobre operaciones (%)',
      commissionHelper: 'Ingresá el porcentaje total que te cobra el broker por operaciones en el mercado secundario.',
      arancelColocadoraLabel: 'Arancel caución colocadora anual (%)',
      arancelColocadoraHelper: 'Porcentaje anual aplicado cuando actuás como colocador/a en cauciones.',
      arancelTomadoraLabel: 'Arancel caución tomadora anual (%)',
      arancelTomadoraHelper: 'Porcentaje anual aplicado cuando tomás cauciones.',
      saveButton: 'Guardar cambios',
      resetButton: 'Restaurar valores iniciales',
      successMessage: 'Comisiones actualizadas.',
      resetMessage: 'Se restauraron los valores iniciales.',
      errorMessage: 'No se pudieron guardar los cambios. Volvé a intentarlo.',
      validationError: 'Ingresá valores mayores o iguales a 0.',
    },
  },
  repo: {
    tooltip: {
      arancel: 'Arancel',
      derechos: 'Derechos de mercado',
      gastosGarantia: 'Gastos de garantía',
      iva: 'IVA sobre gastos',
      totalExpenses: 'Gastos totales',
      accruedInterest: 'Interés devengado',
      baseAmount: 'Monto base',
      netSettlement: 'Neto de liquidación',
      missingConfigTitle: 'Configurá las tasas de caución',
      missingConfigDescription: 'No hay tasas configuradas para {currency} {role}. Completalas en Configuración para habilitar el cálculo de gastos ({missing}).',
      missingRatesFallback: 'tasas pendientes',
    },
    roles: {
      colocadora: 'Colocadora',
      tomadora: 'Tomadora',
    },
    currencies: {
      ARS: 'ARS',
      USD: 'USD',
    },
  },
};

export default strings;
