const strings = {
  locale: 'es-AR',
  app: {
    title: 'Procesador Opciones',
    construction: 'La aplicación está en construcción.',
  },
  navigation: {
    processor: 'Procesador',
    settings: 'Configuración',
  },
  processor: {
    viewControls: {
      previewLabel: 'Vista de resultados',
      callsTab: 'CALLS',
      putsTab: 'PUTS',
      settingsButton: 'Ir a Configuración',
      previewAriaLabel: 'Seleccionar vista de resultados',
    },
    upload: {
      title: 'Procesar operaciones',
      description: 'Seleccioná un archivo CSV con tus operaciones para generar el informe.',
      symbolLabel: 'Símbolo',
      symbolHelper: 'Elegí el símbolo activo para filtrar las operaciones.',
      expirationLabel: 'Vencimiento',
      expirationHelper: 'Elegí el vencimiento activo para procesar el archivo.',
      selectButton: 'Seleccionar archivo',
      noFileSelected: 'Ningún archivo seleccionado',
      processButton: 'Procesar',
      processing: 'Procesando...',
      averagingSwitch: 'Promediar por strike',
    },
    summary: {
      title: 'Resumen',
      calls: 'CALLS',
      puts: 'PUTS',
      total: 'Total',
      averagingOn: 'Promedios activados',
      averagingOff: 'Promedios desactivados',
      processedAt: 'Procesado el',
    },
    actions: {
      title: 'Acciones',
      currentViewPrefix: 'Vista actual:',
      copyActive: 'Copiar vista actual',
      downloadActive: 'Descargar vista actual',
      scopeSection: 'Acciones por conjunto específico',
      viewNames: {
        CALLS: 'CALLS',
        PUTS: 'PUTS',
      },
      copyCalls: 'Copiar CALLS',
      copyPuts: 'Copiar PUTS',
      copyCombined: 'Copiar combinados',
      copySuccess: 'Datos copiados al portapapeles.',
      copyError: 'No se pudo copiar los datos. Intentalo nuevamente.',
      downloadCalls: 'Descargar CALLS',
      downloadPuts: 'Descargar PUTS',
      downloadCombined: 'Descargar combinados',
      downloadError: 'No se pudo generar el archivo para descargar.',
    },
    tables: {
      callsTitle: 'Operaciones CALLS',
      putsTitle: 'Operaciones PUTS',
      quantity: 'Cantidad',
      strike: 'Strike',
      price: 'Precio',
      empty: 'Sin datos para mostrar.',
    },
    warnings: {
      largeFile: 'El archivo supera las 25.000 filas. El procesamiento puede demorar.',
      parseErrors: 'Se detectaron filas con errores durante el análisis del archivo.',
      maxRowsExceeded: 'Se alcanzó el límite de 50.000 filas. Verificá que el archivo esté completo.',
    },
    errors: {
      processingFailed: 'No se pudo procesar el archivo. Verificá el formato e intentá de nuevo.',
    },
  },
  settings: {
    title: 'Configuración',
    description:
      'Personalizá los símbolos, vencimientos y preferencias que usa el procesador para filtrar tus operaciones.',
    storageDisabled:
      'No pudimos acceder al almacenamiento local. Los cambios que hagas no se van a guardar al cerrar la aplicación.',
    resetButton: 'Restaurar valores por defecto',
    resetDescription: 'Volvé a la configuración inicial definida por la aplicación.',
    placeholderTitle: 'Configuración en construcción',
    placeholderBody:
      'Aquí vas a administrar símbolos, vencimientos y preferencias de procesamiento una vez habilitado.',
    symbols: {
      title: 'Símbolos',
      description: 'Gestioná la lista de símbolos disponibles para el procesamiento.',
      inputLabel: 'Nuevo símbolo',
      inputPlaceholder: 'Ej. GGAL',
      inputHelper: 'Ingresá el ticker sin espacios ni caracteres especiales.',
      addButton: 'Agregar',
      errorRequired: 'Ingresá un símbolo.',
      errorDuplicate: 'Ese símbolo ya existe.',
      listLabel: 'Símbolos configurados',
      emptyState: 'Agregá un símbolo para que aparezca en la lista.',
      removeLabel: 'Eliminar símbolo',
      activeLabel: 'Símbolo activo',
    },
    expirations: {
      title: 'Vencimientos',
      description: 'Configurá los vencimientos disponibles y administrá sus sufijos.',
      nameLabel: 'Nombre del vencimiento',
      namePlaceholder: 'Ej. Marzo',
      suffixLabel: 'Sufijo',
      suffixPlaceholder: 'Ej. MAR',
    helper: 'Podés reutilizar el nombre para agregar más sufijos.',
    suffixHelper: 'Los sufijos se guardan en mayúsculas.',
      addButton: 'Agregar',
      errorNameRequired: 'Ingresá un nombre de vencimiento.',
      errorSuffixRequired: 'Ingresá al menos un sufijo.',
      errorSuffixDuplicate: 'Ese sufijo ya existe para este vencimiento.',
      listLabel: 'Vencimientos configurados',
      emptyState: 'Agregá un vencimiento para que aparezca en la lista.',
      activeLabel: 'Vencimiento activo',
      removeLabel: 'Eliminar vencimiento',
      removeSuffixLabel: 'Quitar sufijo',
    },
  },
};

export default strings;
